#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a 'URxvt:emacs:*' desktop='^2'
bspc rule -a Chromium desktop='^4' state=floating follow=on
bspc rule -a vlc desktop='^5' state=floating follow=on
bspc rule -a okular desktop='^3' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Peek state=floating center=true
bspc rule -a Blender state=floating
bspc rule -a Steam state=floating
#bspc config click_to_focus button1
bspc config focus_follows_pointer true

#xrdb ~/.Xresources
urxvt -name emacs -e emacs -nw &

# source the colors
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

feh --bg-center $HOME/Images/wallpapers/blue-gray-lake.jpg
wal -s -R
$HOME/.config/polybar/launch.sh

bspc rule -a 'URxvt:mainterm:*' desktop='^1' state=floating center=true rectangle=1000x600+0+0
urxvt -name mainterm &
conky &
